#property strict
#property copyright "Generated by AI Assistant"
#property link      ""
#property version   "1.00"
#property description "Stochastic Oscillator Expert Advisor with fully configurable parameters"

// ==============================
// Inputs: Indicator Parameters
// ==============================
input int      InpKPeriod           = 5;     // %K period
input int      InpDPeriod           = 3;     // %D period
input int      InpSlowing           = 3;     // Slowing
input int      InpMAMethod          = MODE_SMA; // MA method (0=SMA,1=EMA,2=SMMA,3=LWMA)
input int      InpPriceField        = 0;     // Price (0=Low/High, 1=Close/Close)
input ENUM_TIMEFRAMES InpStochTF    = PERIOD_CURRENT; // Stochastic timeframe
input double   InpOverbought        = 80.0;  // Overbought level
input double   InpOversold          = 20.0;  // Oversold level
input bool     InpUseZoneFilter     = true;  // Require crosses to occur beyond levels (under oversold / above overbought)

// ==============================
// Inputs: Strategy & Trade Logic
// ==============================
input bool     InpAllowBuy          = true;  // Allow Buy trades
input bool     InpAllowSell         = true;  // Allow Sell trades
input bool     InpCloseOnReverse    = true;  // Close on opposite signal
input bool     InpOneTradePerBar    = true;  // Trade only once per new bar

// ==============================
// Inputs: Money Management
// ==============================
input bool     InpUseRiskPercent    = false; // Use risk % per trade
input double   InpRiskPercent       = 1.0;   // Risk percent (if enabled)
input double   InpFixedLot          = 0.10;  // Fixed lot (if risk disabled)
input double   InpMinLot            = 0.01;  // Minimum lot size
input double   InpMaxLot            = 100.0; // Maximum lot size

// ==============================
// Inputs: Trade Parameters
// ==============================
input int      InpStopLossPips      = 200;   // Stop Loss (pips)
input int      InpTakeProfitPips    = 400;   // Take Profit (pips), 0 = none
input int      InpTrailingStopPips  = 150;   // Trailing Stop (pips), 0 = off
input int      InpTrailingStepPips  = 20;    // Trailing step (pips)
input int      InpSlippagePips      = 3;     // Slippage (pips)
input int      InpMaxSpreadPips     = 20;    // Max allowed spread (pips), 0 = ignore
input int      InpMaxOpenPositions  = 1;     // Max open positions for this symbol/magic

// ==============================
// Inputs: Session & Misc
// ==============================
input int      InpStartHour         = 0;     // Trading start hour (server time)
input int      InpEndHour           = 24;    // Trading end hour (server time, 24 = all day)
input bool     InpECNBroker         = true;  // Use ECN compatible order placement
input int      InpMagicNumber       = 20250812; // Magic Number
input int      InpDebugLevel        = 1;     // 0=None, 1=Basic, 2=Verbose

// ==============================
// Global state
// ==============================
datetime g_lastTradeBarTime = 0;

// ==============================
// Utility functions
// ==============================
double PipInPoints()
{
   if (Digits == 3 || Digits == 5) return 10.0 * Point;
   return Point;
}

int SlippageInPoints()
{
   return (int)MathRound(InpSlippagePips * PipInPoints() / Point);
}

int PipsToPoints(int pips)
{
   return (int)MathRound(pips * PipInPoints() / Point);
}

double NormalizePrice(double price)
{
   return NormalizeDouble(price, (int)MarketInfo(Symbol(), MODE_DIGITS));
}

bool IsNewBar()
{
   datetime currentBarTime = iTime(Symbol(), Period(), 0);
   if (currentBarTime != g_lastTradeBarTime)
   {
      g_lastTradeBarTime = currentBarTime;
      return true;
   }
   return false;
}

bool IsTradingSession()
{
   int hourNow = TimeHour(TimeCurrent());
   if (InpEndHour >= 24) return true;
   if (InpStartHour <= InpEndHour)
      return (hourNow >= InpStartHour && hourNow < InpEndHour);
   // Overnight session (e.g. 22 -> 6)
   return (hourNow >= InpStartHour || hourNow < InpEndHour);
}

bool SpreadOk()
{
   if (InpMaxSpreadPips <= 0) return true;
   double spreadPips = (MarketInfo(Symbol(), MODE_SPREAD) * Point) / PipInPoints();
   return spreadPips <= InpMaxSpreadPips + 1e-6;
}

int CountOpenPositions()
{
   int count = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if (!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if (OrderSymbol() != Symbol()) continue;
      if (OrderMagicNumber() != InpMagicNumber) continue;
      if (OrderType() == OP_BUY || OrderType() == OP_SELL) count++;
   }
   return count;
}

bool CloseAllByType(int orderType)
{
   bool allClosed = true;
   for (int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if (!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if (OrderSymbol() != Symbol()) continue;
      if (OrderMagicNumber() != InpMagicNumber) continue;
      if (OrderType() != orderType) continue;

      bool closed = false;
      if (orderType == OP_BUY)
         closed = OrderClose(OrderTicket(), OrderLots(), Bid, SlippageInPoints(), clrRed);
      else if (orderType == OP_SELL)
         closed = OrderClose(OrderTicket(), OrderLots(), Ask, SlippageInPoints(), clrBlue);

      if (!closed)
      {
         allClosed = false;
         if (InpDebugLevel >= 1)
            Print("OrderClose failed ", GetLastError(), " ticket=", OrderTicket());
      }
   }
   return allClosed;
}

void ApplyTrailingStop()
{
   if (InpTrailingStopPips <= 0) return;
   double tsPoints = PipsToPoints(InpTrailingStopPips) * Point;
   double stepPoints = MathMax(Point, PipsToPoints(InpTrailingStepPips) * Point);

   for (int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if (!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if (OrderSymbol() != Symbol()) continue;
      if (OrderMagicNumber() != InpMagicNumber) continue;

      if (OrderType() == OP_BUY)
      {
         double newSL = Bid - tsPoints;
         newSL = NormalizePrice(newSL);
         if (OrderStopLoss() < newSL && (Bid - OrderOpenPrice()) > tsPoints + stepPoints)
         {
            if (!OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen))
            {
               if (InpDebugLevel >= 1)
                  Print("OrderModify (trail buy) failed ", GetLastError(), " ticket=", OrderTicket());
            }
         }
      }
      else if (OrderType() == OP_SELL)
      {
         double newSL = Ask + tsPoints;
         newSL = NormalizePrice(newSL);
         if ((OrderStopLoss() == 0.0 || OrderStopLoss() > newSL) && (OrderOpenPrice() - Ask) > tsPoints + stepPoints)
         {
            if (!OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen))
            {
               if (InpDebugLevel >= 1)
                  Print("OrderModify (trail sell) failed ", GetLastError(), " ticket=", OrderTicket());
            }
         }
      }
   }
}

double CalculateLotSize()
{
   double lot = InpFixedLot;
   if (!InpUseRiskPercent) {
      lot = InpFixedLot;
   } else {
      // Risk-based lot size calculation (approximate)
      int slPips = InpStopLossPips;
      if (slPips <= 0) slPips = 1; // avoid div by zero
      double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
      double tickSize  = MarketInfo(Symbol(), MODE_TICKSIZE);
      double pipValuePerLot = (PipInPoints() / tickSize) * tickValue; // money per pip for 1 lot
      double riskMoney = AccountBalance() * InpRiskPercent / 100.0;
      double lotByRisk = riskMoney / (slPips * pipValuePerLot);
      lot = lotByRisk;
   }
   // Clamp to broker limits and step
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   lot = MathMax(lot, MathMax(minLot, InpMinLot));
   lot = MathMin(lot, MathMin(maxLot, InpMaxLot));
   lot = MathFloor(lot / lotStep) * lotStep;
   lot = NormalizeDouble(lot, 2);
   return lot;
}

bool PlaceOrder(int type, double slPrice, double tpPrice)
{
   double lots = CalculateLotSize();
   int ticket = -1;

   if (InpECNBroker)
   {
      // ECN: open without SL/TP, then modify
      if (type == OP_BUY)
         ticket = OrderSend(Symbol(), OP_BUY, lots, Ask, SlippageInPoints(), 0, 0, "StochEA BUY", InpMagicNumber, 0, clrBlue);
      else
         ticket = OrderSend(Symbol(), OP_SELL, lots, Bid, SlippageInPoints(), 0, 0, "StochEA SELL", InpMagicNumber, 0, clrRed);

      if (ticket < 0)
      {
         if (InpDebugLevel >= 1) Print("OrderSend failed ", GetLastError());
         return false;
      }

      if (slPrice > 0 || tpPrice > 0)
      {
         if (!OrderSelect(ticket, SELECT_BY_TICKET))
         {
            if (InpDebugLevel >= 1) Print("OrderSelect after send failed ", GetLastError());
            return false;
         }
         double openPrice = OrderOpenPrice();
         if (!OrderModify(ticket, openPrice, slPrice, tpPrice, 0, clrNONE))
         {
            if (InpDebugLevel >= 1) Print("OrderModify to set SL/TP failed ", GetLastError());
            // not returning false to allow trade to run without SL/TP if broker rejects
         }
      }
      return true;
   }
   else
   {
      if (type == OP_BUY)
         ticket = OrderSend(Symbol(), OP_BUY, lots, Ask, SlippageInPoints(), slPrice, tpPrice, "StochEA BUY", InpMagicNumber, 0, clrBlue);
      else
         ticket = OrderSend(Symbol(), OP_SELL, lots, Bid, SlippageInPoints(), slPrice, tpPrice, "StochEA SELL", InpMagicNumber, 0, clrRed);

      if (ticket < 0)
      {
         if (InpDebugLevel >= 1) Print("OrderSend failed ", GetLastError());
         return false;
      }
      return true;
   }
}

void GetSLTPPrices(int type, double &slPrice, double &tpPrice)
{
   slPrice = 0.0;
   tpPrice = 0.0;

   int slPts = PipsToPoints(InpStopLossPips);
   int tpPts = PipsToPoints(InpTakeProfitPips);

   if (type == OP_BUY)
   {
      if (InpStopLossPips > 0) slPrice = NormalizePrice(Bid - slPts * Point);
      if (InpTakeProfitPips > 0) tpPrice = NormalizePrice(Bid + tpPts * Point);
   }
   else if (type == OP_SELL)
   {
      if (InpStopLossPips > 0) slPrice = NormalizePrice(Ask + slPts * Point);
      if (InpTakeProfitPips > 0) tpPrice = NormalizePrice(Ask - tpPts * Point);
   }
}

// ==============================
// Signals
// ==============================
void ReadStochastic(double &kCur, double &dCur, double &kPrev, double &dPrev)
{
   kCur  = iStochastic(Symbol(), InpStochTF, InpKPeriod, InpDPeriod, InpSlowing, InpMAMethod, InpPriceField, MODE_MAIN,   0);
   dCur  = iStochastic(Symbol(), InpStochTF, InpKPeriod, InpDPeriod, InpSlowing, InpMAMethod, InpPriceField, MODE_SIGNAL, 0);
   kPrev = iStochastic(Symbol(), InpStochTF, InpKPeriod, InpDPeriod, InpSlowing, InpMAMethod, InpPriceField, MODE_MAIN,   1);
   dPrev = iStochastic(Symbol(), InpStochTF, InpKPeriod, InpDPeriod, InpSlowing, InpMAMethod, InpPriceField, MODE_SIGNAL, 1);
}

bool IsBuySignal(double kCur, double dCur, double kPrev, double dPrev)
{
   bool crossUp = (kPrev <= dPrev && kCur > dCur);
   if (!crossUp) return false;
   if (InpUseZoneFilter)
   {
      // At least one of the points below oversold
      if (!(kCur < InpOversold || kPrev < InpOversold || dCur < InpOversold || dPrev < InpOversold)) return false;
   }
   return true;
}

bool IsSellSignal(double kCur, double dCur, double kPrev, double dPrev)
{
   bool crossDown = (kPrev >= dPrev && kCur < dCur);
   if (!crossDown) return false;
   if (InpUseZoneFilter)
   {
      // At least one of the points above overbought
      if (!(kCur > InpOverbought || kPrev > InpOverbought || dCur > InpOverbought || dPrev > InpOverbought)) return false;
   }
   return true;
}

bool HasOpenPositionOfType(int orderType)
{
   for (int i = OrdersTotal() - 1; i >= 0; i--)
   {
      if (!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if (OrderSymbol() != Symbol()) continue;
      if (OrderMagicNumber() != InpMagicNumber) continue;
      if (OrderType() == orderType) return true;
   }
   return false;
}

// ==============================
// Standard handlers
// ==============================
int OnInit()
{
   if (InpDebugLevel >= 1)
      Print("Stochastic_Advisor initialized on ", Symbol(), " TF=", Period());
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   if (InpDebugLevel >= 1) Print("Stochastic_Advisor deinitialized. Reason=", reason);
}

void OnTick()
{
   // Safety checks
   if (!IsTradingSession()) return;
   if (!SpreadOk()) return;

   // Only on new bar if required
   if (InpOneTradePerBar && !IsNewBar())
   {
      // Still apply trailing stop on every tick
      ApplyTrailingStop();
      return;
   }

   // Read stochastic values
   double kCur, dCur, kPrev, dPrev;
   ReadStochastic(kCur, dCur, kPrev, dPrev);

   // Optional close on reverse
   if (InpCloseOnReverse)
   {
      if (IsBuySignal(kCur, dCur, kPrev, dPrev))
         CloseAllByType(OP_SELL);
      if (IsSellSignal(kCur, dCur, kPrev, dPrev))
         CloseAllByType(OP_BUY);
   }

   // Respect max open positions
   int openCount = CountOpenPositions();
   if (openCount < InpMaxOpenPositions)
   {
      // Entry logic
      if (InpAllowBuy && IsBuySignal(kCur, dCur, kPrev, dPrev) && !HasOpenPositionOfType(OP_BUY))
      {
         double sl, tp; GetSLTPPrices(OP_BUY, sl, tp);
         PlaceOrder(OP_BUY, sl, tp);
      }
      if (InpAllowSell && IsSellSignal(kCur, dCur, kPrev, dPrev) && !HasOpenPositionOfType(OP_SELL))
      {
         double sl, tp; GetSLTPPrices(OP_SELL, sl, tp);
         PlaceOrder(OP_SELL, sl, tp);
      }
   }

   // Manage trailing stops
   ApplyTrailingStop();
}